# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d9e7b357ab6dc6a6100d19836f2daea9c02063fc56d7aa30c74570243f8cd23f8d4889dc671c4a0ec08c8f937c7e34210ef7f01f5e538e084b2d10974ea20a6

test:
  secret_key_base: 29859354b70350b710d482c70a55c937f8b6c61453eeca505e6d1a30575c03d6722d9a890002fc50ed1492c6d93172287139aa45f7b5d470c2365cdc0378d77d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
